// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkSmart;

#nullable disable

namespace ParkSmart.Migrations
{
    [DbContext(typeof(ParkSmartDbContext))]
    partial class ParkSmartDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParkSmart.Cajon", b =>
                {
                    b.Property<Guid>("cajonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("estadoActual")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("nivelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("numeroCajon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("cajonId");

                    b.HasIndex("nivelId", "numeroCajon")
                        .IsUnique();

                    b.ToTable("Cajones");
                });

            modelBuilder.Entity("ParkSmart.Nivel", b =>
                {
                    b.Property<Guid>("nivelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("capacidad")
                        .HasColumnType("int");

                    b.Property<int>("numeroPiso")
                        .HasColumnType("int");

                    b.Property<Guid>("sedeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("nivelId");

                    b.HasIndex("sedeId");

                    b.ToTable("Niveles");
                });

            modelBuilder.Entity("ParkSmart.Reserva", b =>
                {
                    b.Property<Guid>("reservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("cajonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("creadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("duracionEstimadaHoras")
                        .HasColumnType("int");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("fechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<string>("placaVehiculo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("reservaId");

                    b.HasIndex("cajonId");

                    b.HasIndex("creadoPorUsuarioId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("ParkSmart.Sede", b =>
                {
                    b.Property<Guid>("sedeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("creadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("montoMaximoMulta")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("multaConTope")
                        .HasColumnType("bit");

                    b.Property<decimal>("multaPorHora")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("passwordAcceso")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("tarifaPorHora")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("sedeId");

                    b.HasIndex("creadoPorUsuarioId");

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("ParkSmart.Ticket", b =>
                {
                    b.Property<Guid>("ticketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("cajonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("horaEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("horaSalida")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("montoTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("placaVehiculo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ticketId");

                    b.HasIndex("cajonId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("ParkSmart.Usuario", b =>
                {
                    b.Property<Guid>("usuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("usuarioId");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ParkSmart.Cajon", b =>
                {
                    b.HasOne("ParkSmart.Nivel", "nivel")
                        .WithMany("cajones")
                        .HasForeignKey("nivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("nivel");
                });

            modelBuilder.Entity("ParkSmart.Nivel", b =>
                {
                    b.HasOne("ParkSmart.Sede", "sede")
                        .WithMany("niveles")
                        .HasForeignKey("sedeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sede");
                });

            modelBuilder.Entity("ParkSmart.Reserva", b =>
                {
                    b.HasOne("ParkSmart.Cajon", "cajon")
                        .WithMany("reservas")
                        .HasForeignKey("cajonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkSmart.Usuario", "creadoPor")
                        .WithMany("reservas")
                        .HasForeignKey("creadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("cajon");

                    b.Navigation("creadoPor");
                });

            modelBuilder.Entity("ParkSmart.Sede", b =>
                {
                    b.HasOne("ParkSmart.Usuario", "creadoPor")
                        .WithMany("sedesCreadas")
                        .HasForeignKey("creadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("creadoPor");
                });

            modelBuilder.Entity("ParkSmart.Ticket", b =>
                {
                    b.HasOne("ParkSmart.Cajon", "cajon")
                        .WithMany("tickets")
                        .HasForeignKey("cajonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("cajon");
                });

            modelBuilder.Entity("ParkSmart.Cajon", b =>
                {
                    b.Navigation("reservas");

                    b.Navigation("tickets");
                });

            modelBuilder.Entity("ParkSmart.Nivel", b =>
                {
                    b.Navigation("cajones");
                });

            modelBuilder.Entity("ParkSmart.Sede", b =>
                {
                    b.Navigation("niveles");
                });

            modelBuilder.Entity("ParkSmart.Usuario", b =>
                {
                    b.Navigation("reservas");

                    b.Navigation("sedesCreadas");
                });
#pragma warning restore 612, 618
        }
    }
}
